// <auto-generated />
using System;
using GoBuddy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoBuddy.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoBuddy.Domain.Entities.RideRequest", b =>
                {
                    b.Property<int>("PK_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DropupLatitude")
                        .HasColumnType("float");

                    b.Property<double>("DropupLongitude")
                        .HasColumnType("float");

                    b.Property<int>("FK_RideSession_ID")
                        .HasColumnType("int");

                    b.Property<int>("FK_User_ID")
                        .HasColumnType("int");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("float");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PK_ID");

                    b.HasIndex("FK_RideSession_ID");

                    b.HasIndex("FK_User_ID");

                    b.ToTable("RideRequests");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.RideSession", b =>
                {
                    b.Property<int>("PK_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("float");

                    b.Property<int>("FK_Driver_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPassengersInRide")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PK_ID");

                    b.HasIndex("FK_Driver_ID");

                    b.HasIndex("CurrentLatitude", "CurrentLongitude");

                    b.ToTable("RideSessions");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.User", b =>
                {
                    b.Property<int>("PK_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserPin")
                        .HasColumnType("int");

                    b.HasKey("PK_ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("PK_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_ID"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FK_user_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PK_ID");

                    b.HasIndex("FK_user_ID");

                    b.HasIndex("VehicleNo")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.RideRequest", b =>
                {
                    b.HasOne("GoBuddy.Domain.Entities.RideSession", "RideSession")
                        .WithMany("RideRequests")
                        .HasForeignKey("FK_RideSession_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoBuddy.Domain.Entities.User", "Passenger")
                        .WithMany("RideRequests")
                        .HasForeignKey("FK_User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("RideSession");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.RideSession", b =>
                {
                    b.HasOne("GoBuddy.Domain.Entities.User", "Driver")
                        .WithMany("RideSessions")
                        .HasForeignKey("FK_Driver_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("GoBuddy.Domain.Entities.User", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("FK_user_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.RideSession", b =>
                {
                    b.Navigation("RideRequests");
                });

            modelBuilder.Entity("GoBuddy.Domain.Entities.User", b =>
                {
                    b.Navigation("RideRequests");

                    b.Navigation("RideSessions");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
